name: &project_name ${COMPOSE_PROJECT_NAME}

services:

  squid:
    container_name: *project_name
    image: ${IMAGE_REPOSITORY}:${IMAGE_TAG}
    build:
      context: .
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        ALPINE_DIGEST: ${ALPINE_DIGEST}
        SQUID_VERSION: ${SQUID_VERSION}
        SQUID_ARCHIVE: ${SQUID_ARCHIVE}
        SQUID_ARCHIVE_DIGEST: ${SQUID_ARCHIVE_DIGEST}
        SQUID_SIGNATURE: ${SQUID_SIGNATURE}
        SQUID_SIGNATURE_DIGEST: ${SQUID_SIGNATURE_DIGEST}
    volumes:
      - cache:/var/cache/squid
      - ./Dockerfile.d/etc/squid.conf:/etc/squid/squid.conf:ro,z
      - ./Dockerfile.d/etc/storeid_database.txt:/etc/squid/storeid_database.txt:ro,z
      - ${TLS_CA_PEM}:/etc/squid/ssl/CA.pem:ro,z
    ports:
      - 3128:3128
    restart: ${RESTART_POLICY}

volumes:
  cache:
    name: *project_name

networks:
  default:
    name: *project_name
    driver: bridge
    enable_ipv6: true
