.env:
	cat << EOF > .env
	VERBOSE=$(VERBOSE)
	COLORS=$(COLORS)
	COMPOSE_PROJECT_NAME=$(COMPOSE_PROJECT_NAME)
	BUILDKIT_PROGRESS=$(BUILDKIT_PROGRESS)
	ALPINE_VERSION=$(ALPINE_VERSION)
	ALPINE_DIGEST=$(ALPINE_DIGEST)
	SQUID_VERSION=$(SQUID_VERSION)
	SQUID_ARCHIVE_DIGEST=$(SQUID_ARCHIVE_DIGEST)
	SQUID_SIGNATURE_DIGEST=$(SQUID_SIGNATURE_DIGEST)
	IMAGE_REPOSITORY=$(IMAGE_REPOSITORY)
	IMAGE_TAG=$(IMAGE_TAG)
	TLS_CA_PEM=$(TLS_CA_PEM)
	RESTART_POLICY=$(RESTART_POLICY)
	EOF

.DEFAULT: .env
	$(MAKE) help
