.env:
	cat << EOF > .env
	VERBOSE=$(VERBOSE)
	DOCKER=$(DOCKER)
	COMPOSE_PROJECT_NAME=$(COMPOSE_PROJECT_NAME)
	BUILDKIT_PROGRESS=$(BUILDKIT_PROGRESS)
	ALPINE_VERSION=$(ALPINE_VERSION)
	SQUID_VERSION=$(SQUID_VERSION)
	IMAGE_REPOSITORY=$(IMAGE_REPOSITORY)
	IMAGE_TAG=$(IMAGE_TAG)
	TLS_CA_CERT_AND_KEY=$(TLS_CA_CERT_AND_KEY)
	RESTART_POLICY=$(RESTART_POLICY)
	EOF

%:: .env;
